
version: '3'
services:
  nextjs:
    image: node:20.10.0
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app
    # command: "npm install && npm run dev"
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    # networks:
    #   - nginx
    tty: true
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/src/app
    ports:
      - "8080:80"
    depends_on:
      - nextjs
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextjs_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
volumes:
  mysql-data:
  node_modules:
